CK_ROOT := ../..

CK_LIB_NAME := libtremor.a

CK_INCLUDE_DIRS := $(CK_ROOT)/ext/libogg/include

CK_C_FLAGS := -Wno-unused-variable -Wno-duplicate-decl-specifier

CK_C_SRC_FILES := \
    block.c \
    codebook.c \
    floor0.c \
    floor1.c \
    info.c \
    mapping0.c \
    mdct.c \
    registry.c \
    res012.c \
    sharedbook.c \
    synthesis.c \
    vorbisfile.c \
    window.c 

include $(CK_ROOT)/build/Makefile-common

