/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crickettechnology_audio_Bank */

#ifndef _Included_com_crickettechnology_audio_Bank
#define _Included_com_crickettechnology_audio_Bank
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeIsLoaded
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Bank_nativeIsLoaded
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeIsFailed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Bank_nativeIsFailed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crickettechnology_audio_Bank_nativeGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeGetNumSounds
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Bank_nativeGetNumSounds
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeGetSoundName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crickettechnology_audio_Bank_nativeGetSoundName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeNewBank
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Bank_nativeNewBank
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeNewBankAsync
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Bank_nativeNewBankAsync
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeFind
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Bank_nativeFind
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_crickettechnology_audio_Bank
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Bank_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
