/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crickettechnology_audio_EffectBus */

#ifndef _Included_com_crickettechnology_audio_EffectBus
#define _Included_com_crickettechnology_audio_EffectBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeAddEffect
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeAddEffect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeRemoveEffect
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeRemoveEffect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeRemoveAllEffects
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeRemoveAllEffects
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeSetOutputBus
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeSetOutputBus
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeGetOutputBus
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_EffectBus_nativeGetOutputBus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeSetBypassed
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeSetBypassed
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeIsBypassed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_EffectBus_nativeIsBypassed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeSetWetDryRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeSetWetDryRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeGetWetDryRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_EffectBus_nativeGetWetDryRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeNewEffectBus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_EffectBus_nativeNewEffectBus
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeGetGlobalEffectBus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_EffectBus_nativeGetGlobalEffectBus
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_EffectBus
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_EffectBus_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
