/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crickettechnology_audio_Mixer */

#ifndef _Included_com_crickettechnology_audio_Mixer
#define _Included_com_crickettechnology_audio_Mixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeSetName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Mixer_nativeSetName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crickettechnology_audio_Mixer_nativeGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeSetVolume
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Mixer_nativeSetVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeGetVolume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Mixer_nativeGetVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeGetMixedVolume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Mixer_nativeGetMixedVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeSetParent
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Mixer_nativeSetParent
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeGetParent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Mixer_nativeGetParent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeGetMaster
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Mixer_nativeGetMaster
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeNewMixer
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Mixer_nativeNewMixer
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeFind
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Mixer_nativeFind
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_crickettechnology_audio_Mixer
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Mixer_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
