/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crickettechnology_audio_Effect */

#ifndef _Included_com_crickettechnology_audio_Effect
#define _Included_com_crickettechnology_audio_Effect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeSetParam
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Effect_nativeSetParam
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Effect_nativeReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeSetBypassed
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Effect_nativeSetBypassed
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeIsBypassed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Effect_nativeIsBypassed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeSetWetDryRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Effect_nativeSetWetDryRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeGetWetDryRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Effect_nativeGetWetDryRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeNewEffect
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Effect_nativeNewEffect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_crickettechnology_audio_Effect
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Effect_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
