/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crickettechnology_audio_Ck */

#ifndef _Included_com_crickettechnology_audio_Ck
#define _Included_com_crickettechnology_audio_Ck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeInit
 * Signature: (Landroid/app/Activity;Lcom/crickettechnology/audio/Config;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeInit
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeSuspend
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeSuspend
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeResume
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeUpdate
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeGetRenderLoad
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Ck_nativeGetRenderLoad
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeGetClipFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Ck_nativeGetClipFlag
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeResetClipFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeResetClipFlag
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeSetVolumeRampTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Ck_nativeSetVolumeRampTime
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_crickettechnology_audio_Ck
 * Method:    nativeGetVolumeRampTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Ck_nativeGetVolumeRampTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
