/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crickettechnology_audio_Sound */

#ifndef _Included_com_crickettechnology_audio_Sound
#define _Included_com_crickettechnology_audio_Sound
#ifdef __cplusplus
extern "C" {
#endif
#undef com_crickettechnology_audio_Sound_SOUND_SPEED_CENTIMETERS_PER_SECOND
#define com_crickettechnology_audio_Sound_SOUND_SPEED_CENTIMETERS_PER_SECOND 34320.0f
#undef com_crickettechnology_audio_Sound_SOUND_SPEED_METERS_PER_SECOND
#define com_crickettechnology_audio_Sound_SOUND_SPEED_METERS_PER_SECOND 343.2f
#undef com_crickettechnology_audio_Sound_SOUND_SPEED_INCHES_PER_SECOND
#define com_crickettechnology_audio_Sound_SOUND_SPEED_INCHES_PER_SECOND 13512.0f
#undef com_crickettechnology_audio_Sound_SOUND_SPEED_FEET_PER_SECOND
#define com_crickettechnology_audio_Sound_SOUND_SPEED_FEET_PER_SECOND 1126.0f
/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetMixer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetMixer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetMixer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Sound_nativeGetMixer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIsReady
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIsReady
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIsFailed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIsFailed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativePlay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativePlay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIsPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIsPlaying
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetPaused
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIsPaused
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIsPaused
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetLoop
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetLoop
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetLoop
 * Signature: (JLcom/crickettechnology/audio/IntRef;Lcom/crickettechnology/audio/IntRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGetLoop
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetLoopCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetLoopCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetLoopCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Sound_nativeGetLoopCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetCurrentLoop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Sound_nativeGetCurrentLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeReleaseLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeReleaseLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIsLoopReleased
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIsLoopReleased
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetPlayPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetPlayPosition
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetPlayPositionMs
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetPlayPositionMs
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetPlayPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Sound_nativeGetPlayPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetPlayPositionMs
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetPlayPositionMs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetVolume
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetVolume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetMixedVolume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetMixedVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetPan
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetPan
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetPan
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetPan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetPanMatrix
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetPanMatrix
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetPanMatrix
 * Signature: (JLcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGetPanMatrix
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetPitchShift
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetPitchShift
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetPitchShift
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetPitchShift
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetSpeed
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetSpeed
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Sound_nativeGetLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetLengthMs
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGetLengthMs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Sound_nativeGetSampleRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_crickettechnology_audio_Sound_nativeGetChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSetEffectBus
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSetEffectBus
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGetEffectBus
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Sound_nativeGetEffectBus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIs3dEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIs3dEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeIsVirtual
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crickettechnology_audio_Sound_nativeIsVirtual
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dPosition
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dPosition
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGet3dPosition
 * Signature: (JLcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGet3dPosition
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dVelocity
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dVelocity
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGet3dVelocity
 * Signature: (JLcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGet3dVelocity
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dListenerPosition
 * Signature: (FFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dListenerPosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGet3dListenerPosition
 * Signature: (Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGet3dListenerPosition
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dListenerVelocity
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dListenerVelocity
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGet3dListenerVelocity
 * Signature: (Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGet3dListenerVelocity
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dAttenuation
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dAttenuation
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGet3dAttenuation
 * Signature: (Lcom/crickettechnology/audio/IntRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;Lcom/crickettechnology/audio/FloatRef;)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeGet3dAttenuation
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeSet3dSoundSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeSet3dSoundSpeed
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeGet3dSoundSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_crickettechnology_audio_Sound_nativeGet3dSoundSpeed
  (JNIEnv *, jclass);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeNewBankSoundByIndex
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Sound_nativeNewBankSoundByIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeNewBankSoundByName
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Sound_nativeNewBankSoundByName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeNewStreamSound
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_crickettechnology_audio_Sound_nativeNewStreamSound
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_crickettechnology_audio_Sound
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_crickettechnology_audio_Sound_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
